[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_ENV = "production"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_API_BASE_URL"
  NPM_FLAGS = "--omit=dev"

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for Next.js images
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
